export const SUBMIT_VALUE = "SUBMIT_VALUE";
export const FETCH_ERROR = "fetch_error";

export const REQUEST_ALL_STORES = "REQUEST_ALL_STORES";
export const RECEIVE_ALL_STORES = "RECEIVE_ALL_STORES";
export const REQUEST_CREATE_PRODUCTS_CSV = "REQUEST_CREATE_PRODUCTS_CSV";
export const RECEIVE_CREATE_PRODUCTS_CSV = "RECEIVE_CREATE_PRODUCTS_CSV";
