export const SUBMIT_VALUE = "SUBMIT_VALUE";
export const FETCH_ERROR = "fetch_error";

// reporting
export const REQUEST_CURRENT_MEMBERS = "REQUEST_CURRENT_MEMBERS";
export const RECEIVE_CURRENT_MEMBERS = "RECEIVE_CURRENT_MEMBERS";
export const REQUEST_RENEWING_MEMBERS = "REQUEST_RENEWING_MEMBERS";
export const RECEIVE_RENEWING_MEMBERS = "RECEIVE_RENEWING_MEMBERS";
export const REQUEST_NEW_MEMBERS = "REQUEST_NEW_MEMBERS";
export const RECEIVE_NEW_MEMBERS = "RECEIVE_NEW_MEMBERS";
export const REQUEST_EXPIRED_MEMBERS = "REQUEST_EXPIRED_MEMBERS";
export const RECEIVE_EXPIRED_MEMBERS = "RECEIVE_EXPIRED_MEMBERS";
export const REQUEST_EXTENDED_HISTORY = "REQUEST_EXTENDED_HISTORY";
export const RECEIVE_EXTENDED_HISTORY = "RECEIVE_EXTENDED_HISTORY";
export const REQUEST_SALES_ACTIVITY = "REQUEST_SALES_ACTIVITY";
export const RECEIVE_SALES_ACTIVITY = "RECEIVE_SALES_ACTIVITY";
export const REQUEST_MENU_CHANGE = "REQUEST_MENU_CHANGE";
export const RECEIVE_MENU_CHANGE = "RECEIVE_MENU_CHANGE";

export const GET_MEMBER_DETAILS_REQUEST = "GET_MEMBER_DETAILS_REQUEST";
export const GET_MEMBER_DETAILS_SUCCESS = "GET_MEMBER_DETAILS_SUCCESS";
export const GET_MEMBER_DETAILS_FAILURE = "GET_MEMBER_DETAILS_FAILURE";

export const SHOW_MODAL = "SHOW_MODAL";
export const HANDLE_ALL_MEMBERS_EXPORT = "HANDLE_ALL_MEMBERS_EXPORT"
export const UPDATE_ALL_MEMBER_DETAILS = "UPDATE_ALL_MEMBER_DETAILS"

export const FETCH_LOCATION_COUNTRY_REQUEST = "FETCH_LOCATION_COUNTRY_REQUEST";
export const FETCH_LOCATION_COUNTRY_SUCCESS = "FETCH_LOCATION_COUNTRY_SUCCESS";
export const FETCH_LOCATION_COUNTRY_FAILURE = "FETCH_LOCATION_COUNTRY_FAILURE";

export const FETCH_LOCATION_STATE_REQUEST = "FETCH_LOCATION_STATE_REQUEST";
export const FETCH_LOCATION_STATE_SUCCESS = "FETCH_LOCATION_STATE_SUCCESS";
export const FETCH_LOCATION_STATE_FAILURE = "FETCH_LOCATION_STATE_FAILURE";

export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST";