export const SUBMIT_VALUE = "SUBMIT_VALUE";
export const FETCH_ERROR = "fetch_error";

// reporting
export const REQUEST_MENU_CHANGE = "REQUEST_MENU_CHANGE";
export const RECEIVE_MENU_CHANGE = "RECEIVE_MENU_CHANGE";

export const SHOW_MODAL = "SHOW_MODAL";
export const HANDLE_ALL_MEMBERS_EXPORT = "HANDLE_ALL_MEMBERS_EXPORT"

export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST";

export const FETCH_MOST_VIEWED_PRODUCTS_REQUEST = "FETCH_MOST_VIEWED_PRODUCTS_REQUEST";
export const FETCH_MOST_VIEWED_PRODUCTS_SUCCESS = "FETCH_MOST_VIEWED_PRODUCTS_SUCCESS";
export const FETCH_MOST_VIEWED_PRODUCTS_FAILURE = "FETCH_MOST_VIEWED_PRODUCTS_FAILURE";

export const FETCH_ACTIVE_USERS_UID_REQUEST = "FETCH_ACTIVE_USERS_UID_REQUEST";
export const FETCH_ACTIVE_USERS_UID_SUCCESS = "FETCH_ACTIVE_USERS_UID_SUCCESS";
export const FETCH_ACTIVE_USERS_UID_FAILURE = "FETCH_ACTIVE_USERS_UID_FAILURE";

export const FETCH_ACTIVE_USERS_DATA_REQUEST = "FETCH_ACTIVE_USERS_DATA_REQUEST";
export const FETCH_ACTIVE_USERS_DATA_SUCCESS = "FETCH_ACTIVE_USERS_DATA_SUCCESS";
export const FETCH_ACTIVE_USERS_DATA_FAILURE = "FETCH_ACTIVE_USERS_DATA_FAILURE";

export const FETCH_MOST_VIEWED_FILES_REQUEST = "FETCH_MOST_VIEWED_FILES_REQUEST";
export const FETCH_MOST_VIEWED_FILES_SUCCESS = "FETCH_MOST_VIEWED_FILES_SUCCESS";
export const FETCH_MOST_VIEWED_FILES_FAILURE = "FETCH_MOST_VIEWED_FILES_FAILURE";

export const FETCH_INSIGHTS_DATA_REQUEST = "FETCH_INSIGHTS_DATA_REQUEST";
export const FETCH_INSIGHTS_DATA_SUCCESS = "FETCH_INSIGHTS_DATA_SUCCESS";
export const FETCH_INSIGHTS_DATA_FAILURE = "FETCH_INSIGHTS_DATA_FAILURE";

export const FETCH_MONTHLY_ACTIVE_USERS_REQUEST = "FETCH_MONTHLY_ACTIVE_USERS_REQUEST";
export const FETCH_MONTHLY_ACTIVE_USERS_SUCCESS = "FETCH_MONTHLY_ACTIVE_USERS_SUCCESS";
export const FETCH_MONTHLY_ACTIVE_USERS_FAILURE = "FETCH_MONTHLY_ACTIVE_USERS_FAILURE";

export const FETCH_MONTHLY_BANDWIDTH_DATA_REQUEST = "FETCH_MONTHLY_BANDWIDTH_DATA_REQUEST";
export const FETCH_MONTHLY_BANDWIDTH_DATA_SUCCESS = "FETCH_MONTHLY_BANDWIDTH_DATA_SUCCESS";
export const FETCH_MONTHLY_BANDWIDTH_DATA_FAILURE = "FETCH_MONTHLY_BANDWIDTH_DATA_FAILURE";

export const FETCH_FILES_STATISTICS_DATA_REQUEST = "FETCH_FILES_STATISTICS_DATA_REQUEST";
export const FETCH_FILES_STATISTICS_DATA_SUCCESS = "FETCH_FILES_STATISTICS_DATA_SUCCESS";
export const FETCH_FILES_STATISTICS_DATA_FAILURE = "FETCH_FILES_STATISTICS_DATA_FAILURE";

export const FETCH_MONTHLY_FILE_VIEWS_REQUEST = "FETCH_MONTHLY_FILE_VIEWS_REQUEST";
export const FETCH_MONTHLY_FILE_VIEWS_SUCCESS = "FETCH_MONTHLY_FILE_VIEWS_SUCCESS";
export const FETCH_MONTHLY_FILE_VIEWS_FAILURE = "FETCH_MONTHLY_FILE_VIEWS_FAILURE";

export const FETCH_PRODUCT_VIEWS_BY_USER_REQUEST = "FETCH_PRODUCT_VIEWS_BY_USER_REQUEST";
export const FETCH_PRODUCT_VIEWS_BY_USER_SUCCESS = "FETCH_PRODUCT_VIEWS_BY_USER_SUCCESS";
export const FETCH_PRODUCT_VIEWS_BY_USER_FAILURE = "FETCH_PRODUCT_VIEWS_BY_USER_FAILURE";

export const FETCH_USER_CUSTOMER_ID_REQUEST = "FETCH_USER_CUSTOMER_ID_REQUEST";
export const FETCH_USER_CUSTOMER_ID_SUCCESS = "FETCH_USER_CUSTOMER_ID_SUCCESS";
export const FETCH_USER_CUSTOMER_ID_FAILURE = "FETCH_USER_CUSTOMER_ID_FAILURE";

export const FETCH_USER_CONTACT_DETAILS_REQUEST = "FETCH_USER_CONTACT_DETAILS_REQUEST";
export const FETCH_USER_CONTACT_DETAILS_SUCCESS = "FETCH_USER_CONTACT_DETAILS_SUCCESS";
export const FETCH_USER_CONTACT_DETAILS_FAILURE = "FETCH_USER_CONTACT_DETAILS_FAILURE";