export const SUBMIT_VALUE = "SUBMIT_VALUE";
export const FETCH_ERROR = "fetch_error";

export const RECEIVE_NEXT_STEP = "RECEIVE_NEXT_STEP";
export const RECEIVE_PREVIOUS_STEP = "RECEIVE_PREVIOUS_STEP";
export const RECEIVE_SET_STEP = "RECEIVE_SET_STEP";
export const REQUEST_ALL_CONFERENCES = "REQUEST_ALL_CONFERENCES";
export const RECEIVE_ALL_CONFERENCES = "RECEIVE_ALL_CONFERENCES";
export const REQUEST_ALL_STORES = "REQUEST_ALL_STORES";
export const RECEIVE_ALL_STORES = "RECEIVE_ALL_STORES";
export const RECEIVE_STORE_SELECTED_CONFERENCE =
  "RECEIVE_STORE_SELECTED_CONFERENCE";
export const REQUEST_SESSION_TYPES = "REQUEST_SESSION_TYPES";
export const RECEIVE_SESSION_TYPES = "RECEIVE_SESSION_TYPES";
export const REQUEST_ALL_SESSIONS = "REQUEST_ALL_SESSIONS";
export const RECEIVE_ALL_SESSIONS = "RECEIVE_ALL_SESSIONS";
export const REQUEST_ALL_SESSIONS_DETAILS = "REQUEST_ALL_SESSIONS_DETAILS";
export const RECEIVE_ALL_SESSIONS_DETAILS = "RECEIVE_ALL_SESSIONS_DETAILS";
export const RECEIVE_STORE_SELECTED_SESSION_TYPES =
  "RECEIVE_STORE_SELECTED_SESSION_TYPES";
export const REQUEST_CONTACT_GROUPS = "REQUEST_CONTACT_GROUPS";
export const RECEIVE_CONTACT_GROUPS = "RECEIVE_CONTACT_GROUPS";
export const RECEIVE_STORE_CONFERENCE_PRICING =
  "RECEIVE_STORE_CONFERENCE_PRICING";
export const RECEIVE_STORE_SESSION_PRICING = "RECEIVE_STORE_SESSION_PRICING";
export const REQUEST_ABSTRACT_MODULES = "REQUEST_ABSTRACT_MODULES";
export const RECEIVE_ABSTRACT_MODULES = "RECEIVE_ABSTRACT_MODULES";
export const REQUEST_ABSTRACT_FIELDS = "REQUEST_ABSTRACT_FIELDS";
export const RECEIVE_ABSTRACT_FIELDS = "RECEIVE_ABSTRACT_FIELDS";
export const RECEIVE_STORE_ABSTRACT_FIELDS = "RECEIVE_STORE_ABSTRACT_FIELDS";
export const RECEIVE_STORE_CUSTOM_BUNDLES = "RECEIVE_STORE_CUSTOM_BUNDLES";
export const RECEIVE_UPDATE_CUSTOM_BUNDLE_ABSTRACTS =
  "RECEIVE_UPDATE_CUSTOM_BUNDLE_ABSTRACTS";
export const REQUEST_ABSTRACTS = "REQUEST_ABSTRACTS";
export const RECEIVE_ABSTRACTS = "RECEIVE_ABSTRACTS";
export const REQUEST_SESSION_ABSTRACT_CONFIG =
  "REQUEST_SESSION_ABSTRACT_CONFIG";
export const RECEIVE_SESSION_ABSTRACT_CONFIG =
  "RECEIVE_SESSION_ABSTRACT_CONFIG";
export const RECEIVE_UPDATE_CONFERENCE_DETAILS =
  "RECEIVE_UPDATE_CONFERENCE_DETAILS";
export const REQUEST_ATTENDEE_GROUPS = "REQUEST_ATTENDEE_GROUPS";
export const RECEIVE_ATTENDEE_GROUPS = "RECEIVE_ATTENDEE_GROUPS";
export const REQUEST_ADD_PRODUCTS = "REQUEST_ADD_PRODUCTS";
export const RECEIVE_ADD_PRODUCTS = "RECEIVE_ADD_PRODUCTS";
export const REQUEST_CONF_MENUS = "REQUEST_CONF_MENUS";
export const RECEIVE_CONF_MENUS = "RECEIVE_CONF_MENUS";
export const RECEIVE_LOADING_CONF_MENUS = "RECEIVE_LOADING_CONF_MENUS";
export const REQUEST_FETCH_ADD_PROD_CATEGORY =
  "REQUEST_FETCH_ADD_PROD_CATEGORY";
export const RECEIVE_FETCH_ADD_PROD_CATEGORY =
  "RECEIVE_FETCH_ADD_PROD_CATEGORY";
export const MIGRATION_FETCH_ERROR = "MIGRATION_FETCH_ERROR";
export const REQUEST_ADD_PRODUCT_PRICING_AND_ACCESS =
  "REQUEST_ADD_PRODUCT_PRICING_AND_ACCESS";
export const RECEIVE_ADD_PRODUCT_PRICING_AND_ACCESS =
  "RECEIVE_ADD_PRODUCT_PRICING_AND_ACCESS";
export const REQUEST_ADD_RELATION = "REQUEST_ADD_RELATION";
export const RECEIVE_ADD_RELATION = "RECEIVE_ADD_RELATION";
export const REQUEST_PERFORM_ROLLBACK = "REQUEST_PERFORM_ROLLBACK";
export const RECEIVE_PERFORM_ROLLBACK = "RECEIVE_PERFORM_ROLLBACK";
export const REQUEST_UPLOAD_TO_S3 = "REQUEST_UPLOAD_TO_S3";
export const RECEIVE_UPLOAD_TO_S3 = "RECEIVE_UPLOAD_TO_S3";
export const REQUEST_CLEAR_EXECUTE_MIGRATION_STATE =
  "REQUEST_CLEAR_EXECUTE_MIGRATION_STATE";
export const RECEIVE_CLEAR_EXECUTE_MIGRATION_STATE =
  "RECEIVE_CLEAR_EXECUTE_MIGRATION_STATE";
export const REQUEST_START_MIGRATION = "REQUEST_START_MIGRATION";
export const RECEIVE_START_MIGRATION = "RECEIVE_START_MIGRATION";
export const REQUEST_STOP_MIGRATION = "REQUEST_STOP_MIGRATION";
export const RECEIVE_STOP_MIGRATION = "RECEIVE_STOP_MIGRATION";
export const REQUEST_SEND_SLACK_MESSAGE = "REQUEST_SEND_SLACK_MESSAGE";
export const RECEIVE_SEND_SLACK_MESSAGE = "RECEIVE_SEND_SLACK_MESSAGE";
export const REQUEST_FIX_FILE_SIZE = "REQUEST_FIX_FILE_SIZE";
export const RECEIVE_FIX_FILE_SIZE = "RECEIVE_FIX_FILE_SIZE";
export const REQUEST_STORE_WIZARD_CONFIG = "REQUEST_STORE_WIZARD_CONFIG";
export const RECEIVE_STORE_WIZARD_CONFIG = "RECEIVE_STORE_WIZARD_CONFIG";

export const REQUEST_CREDIT_DETAILS = "REQUEST_CREDIT_DETAILS";
export const RECEIVE_CREDIT_DETAILS = "RECEIVE_CREDIT_DETAILS";
export const REQUEST_FORM_DETAILS = "REQUEST_FORM_DETAILS";
export const RECEIVE_FORM_DETAILS = "RECEIVE_FORM_DETAILS";
export const RECEIVE_STORE_CREDITS = "RECEIVE_STORE_CREDITS";
export const RECEIVE_STORE_EVALUATION_SESSIONS =
  "RECEIVE_STORE_EVALUATION_SESSIONS";
export const REQUEST_CLONE_FORM = "REQUEST_CLONE_FORM";
export const RECEIVE_CLONE_FORM = "RECEIVE_CLONE_FORM";
