export const SUBMIT_VALUE = "SUBMIT_VALUE";
export const FETCH_ERROR = "fetch_error";

export const REQUEST_PRODUCT_DETAILS = "REQUEST_PRODUCT_DETAILS";
export const RECEIVE_PRODUCT_DETAILS = "RECEIVE_PRODUCT_DETAILS";
export const REQUEST_MAIN_PRODUCT_DETAILS = "REQUEST_MAIN_PRODUCT_DETAILS";
export const RECEIVE_MAIN_PRODUCT_DETAILS = "RECEIVE_MAIN_PRODUCT_DETAILS";
export const REQUEST_ABSTRACT_MODULES = "REQUEST_ABSTRACT_MODULES";
export const RECEIVE_ABSTRACT_MODULES = "RECEIVE_ABSTRACT_MODULES";
export const REQUEST_ABSTRACT_FIELDS = "REQUEST_ABSTRACT_FIELDS";
export const RECEIVE_ABSTRACT_FIELDS = "RECEIVE_ABSTRACT_FIELDS";
export const REQUEST_PRODUCT_DESCENDANTS = "REQUEST_PRODUCT_DESCENDANTS";
export const RECEIVE_PRODUCT_DESCENDANTS = "RECEIVE_PRODUCT_DESCENDANTS";
export const REQUEST_SESSION_ABSTRACT_CONFIG =
  "REQUEST_SESSION_ABSTRACT_CONFIG";
export const RECEIVE_SESSION_ABSTRACT_CONFIG =
  "RECEIVE_SESSION_ABSTRACT_CONFIG";
export const REQUEST_UPDATE_PRODUCTS = "REQUEST_UPDATE_PRODUCTS";
export const RECEIVE_UPDATE_PRODUCTS = "RECEIVE_UPDATE_PRODUCTS";
export const REQUEST_WIZARD_CONFIG = "REQUEST_WIZARD_CONFIG";
export const RECEIVE_WIZARD_CONFIG = "RECEIVE_WIZARD_CONFIG";
export const REQUEST_FIX_FILE_SIZE="REQUEST_FIX_FILE_SIZE";
export const RECEIVE_FIX_FILE_SIZE="RECEIVE_FIX_FILE_SIZE";